### ISSUE TITLE
Can't set protocol versions of listener

### ISSUE THREAD

**Issue by knopki** [vernemq/vmq-operator#12]
Operator image `vernemq/vmq-operator@sha256:4dc6f9f24b9415dc38346259635b88a8545fceeb3897bcbeeade2eec3951814e` (current `:latest`)

CR like
```yaml
---
apiVersion: vernemq.com/v1alpha1
kind: VerneMQ
metadata:
  labels:
    vernemq: main
  name: main
spec:
  baseImage: vernemq/vernemq
  config:
    listeners:
      - address: 0.0.0.0
        port: 1883
        protocolVersions: '3,4,5'
  size: 1
  version: 1.9.2
```

Error in `vernemq-main-0` pod's log:
```
13:33:37.888 [error] Execute error: ["vmq-admin","listener","start","address=0.0.0.0","port=1883","--protocol_versions=3,4,5"] error {badmatch,{error,{invalid_key,"protocol_versions"}}}
```

Looks like operator use `protocol_versions` argument instead of [allowed_protocol_versions](https://github.com/vernemq/vernemq/blob/8843813441d158fef6a5fe2d379dc0b78f2a259f/apps/vmq_server/src/vmq_listener_cli.erl#L55).
