### ISSUE TITLE
Not able to accept EULA

### ISSUE THREAD

**Issue by dannyyy** [vernemq/vmq-operator#18]
Hi,

I'm trying to use this operator. But I haven't found any way to startup the container. The logs always claims, that the EULA has not been accepted. If I use the Helm Chart or the Docker image by its own, then there is no issue as along as I define the needed environment variable.

Please have a look to the definition I use:
```
apiVersion: vernemq.com/v1alpha1
kind: VerneMQ
metadata:
  labels:
    vernemq: k8s
  name: vernemq
spec:
  baseImage: vernemq/vernemq
  config:
    configs:
    - name: allow_register_during_netsplit
      value: "on"
    - name: allow_publish_during_netsplit
      value: "on"
    - name: allow_subscribe_during_netsplit
      value: "on"
    - name: allow_unsubscribe_during_netsplit
      value: "on"
    listeners:
    - address: 0.0.0.0
      port: 1883
    plugins: []
  serviceAccountName: vernemq-k8s
  size: 2
  version: 1.10.1
  env:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
```

Whats wrong here?
